name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Generate Docs
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run docs
    - uses: peaceiris/actions-gh-pages@v3.7.0-8
    - name: Publish Docs to GitHub Pages
    - with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        destination_dir: ./docs/
        keep_files: true