name: Publish GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run docs

  publish-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./
          exclude_assets: ".*ignore,.github,!(docs|lib),lib/__tests__"
          keep_files: true
