name: Publish Docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run docs
      - name: Publish Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./test
          exclude_assets: .*,*,.git,node_modules,!(.git|docs|lib|node_modules)/**,lib/__tests__
          keep_files: true
